# Generated by Django 4.1.7 on 2023-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=8)),
                ('setor', models.CharField(max_length=30)),
                ('salario', models.CharField(max_length=10)),
            ],
        ),
    ]
